# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
        ),
    ]
